#!/bin/bash
# ============================================================
# Deploy Bolt12 Server to an Umbrel node via SSH (standalone, no app store).
# Usage: bash deploy-umbrel.sh [umbrel-ip] [ssh-user]
#
# Uses silex-bolt12-server/docker-compose.standalone.yml with the prebuilt
# ghcr.io images — no local build or source transfer required. Your LND node
# must expose gRPC :10009 and REST :8080 on the LAN (Umbrel's Lightning app
# does this by default).
# ============================================================
set -euo pipefail

UMBREL_IP="${1:-192.168.1.55}"
UMBREL_USER="${2:-umbrel}"
WEB_PORT="${WEB_PORT:-3001}"
REMOTE_DIR="bolt12-server"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_SRC="${SCRIPT_DIR}/silex-bolt12-server/docker-compose.standalone.yml"
SSH="ssh ${UMBREL_USER}@${UMBREL_IP}"

echo "================================================"
echo "   BOLT12 SERVER - DEPLOY TO UMBREL (standalone)"
echo "================================================"
echo "Target: ${UMBREL_USER}@${UMBREL_IP}  (web port ${WEB_PORT})"
echo ""

# ---- 1. SSH connectivity ----
echo "[1/5] Testing SSH connection..."
if ! ssh -o ConnectTimeout=5 -o BatchMode=yes "${UMBREL_USER}@${UMBREL_IP}" "echo ok" 2>/dev/null; then
    echo "SSH key auth not configured — setting it up (you'll be asked for the password once)."
    ssh-copy-id "${UMBREL_USER}@${UMBREL_IP}" || echo "[INFO] ssh-copy-id unavailable; continuing with password auth."
fi

# ---- 2. Locate LND's data directory on the node ----
echo ""
echo "[2/5] Locating LND data directory..."
LND_DATA_DIR=$($SSH '
    for d in \
        "$HOME/umbrel/app-data/lightning/data/lnd" \
        "/home/umbrel/umbrel/app-data/lightning/data/lnd" \
        "$HOME/umbrel/lnd"; do
        if [ -f "$d/tls.cert" ]; then echo "$d"; exit 0; fi
    done
    exit 1
') || { echo "[ERROR] Could not find LND data dir (tls.cert) on the node. Is the Lightning app installed?"; exit 1; }
echo "[OK] LND data dir: ${LND_DATA_DIR}"

# ---- 3. Remote dir + reuse-or-generate API key ----
echo ""
echo "[3/5] Preparing remote directory and API key..."
$SSH "mkdir -p ${REMOTE_DIR}"
API_KEY=$($SSH "
    if [ -f ${REMOTE_DIR}/.env ] && grep -q '^API_KEY=.\\+' ${REMOTE_DIR}/.env; then
        grep '^API_KEY=' ${REMOTE_DIR}/.env | cut -d= -f2
    else
        node -e 'console.log(require(\"crypto\").randomBytes(32).toString(\"hex\"))' 2>/dev/null \
            || head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'
    fi
")

# ---- 4. Transfer compose + write .env ----
echo ""
echo "[4/5] Transferring compose file and writing .env..."
scp -q "${COMPOSE_SRC}" "${UMBREL_USER}@${UMBREL_IP}:${REMOTE_DIR}/docker-compose.yml"

# Unquoted heredoc so the variables below expand locally before being written.
$SSH "cat > ${REMOTE_DIR}/.env" << ENVEOF
# Bolt12 Server - generated by deploy-umbrel.sh
LND_HOST=${UMBREL_IP}
LND_DATA_DIR=${LND_DATA_DIR}
WEB_PORT=${WEB_PORT}
API_KEY=${API_KEY}
LNURL_DOMAIN=
LNURL_USERNAME=pay
LNURL_MIN_MSATS=1000
LNURL_MAX_MSATS=10000000000
ENVEOF
echo "[OK] .env written  (API key: ${API_KEY:0:8}…)"

# ---- 5. Pull images and start ----
echo ""
echo "[5/5] Pulling images and starting containers..."
$SSH "cd ${REMOTE_DIR} && docker compose down 2>/dev/null || true && docker compose pull && docker compose up -d"

# ---- Verification ----
echo ""
echo "================================================"
echo "   VERIFICATION"
echo "================================================"
HEALTH=""
for attempt in 1 2 3 4 5; do
    HEALTH=$(curl -sS --max-time 5 "http://${UMBREL_IP}:${WEB_PORT}/health" 2>/dev/null || true)
    echo "$HEALTH" | grep -q '"status":"ok"' && break
    echo "[INFO] Health attempt ${attempt}/5 not ready yet, retrying in 5s..."
    sleep 5
done

if echo "$HEALTH" | grep -q '"status":"ok"'; then
    echo "[OK] Server is online!"
    echo "  Dashboard : http://${UMBREL_IP}:${WEB_PORT}"
    echo "  Health    : http://${UMBREL_IP}:${WEB_PORT}/health"
    echo "  API Key   : ${API_KEY}"
else
    echo "[!] Not responding yet. Container status:"
    $SSH "cd ${REMOTE_DIR} && docker compose ps" || true
    echo ""
    echo "Logs:  ssh ${UMBREL_USER}@${UMBREL_IP} 'cd ${REMOTE_DIR} && docker compose logs --tail=50 web lndk'"
fi

echo ""
echo "================================================"
echo "   DEPLOY COMPLETE"
echo "================================================"
